production:
  adapter: postgresql
  database: client_app_production

development:
  adapter: postgresql
  database: client_app_development

test: &test
  adapter: postgresql
  database: client_app_test

cucumber:
  <<: *test

